name: ProtectionStones
version: ${version}
description: ${description}
authors: [EspiDev]

depend: [WorldGuard, WorldEdit]
softdepend: [Vault, PlaceholderAPI, LuckPerms]
main: dev.espi.protectionstones.ProtectionStones
api-version: 1.17

permissions:
  protectionstones.create:
    description: Protect a region by placing a ProtectionStones block.
    default: op
  protectionstones.destroy:
    description: Allow players to remove their own protected regions (block break).
    default: op
  protectionstones.unclaim:
    description: Allow players to unclaim their region using /ps unclaim.
    default: op
  protectionstones.unclaim.remote:
    description: Allow players to unclaim their region remotely using /ps unclaim [list|region-id].
    default: op
  protectionstones.view:
    description: Allows players the use of /ps view in their own regions.
    default: op
  protectionstones.view.others:
    description: Allows players the use of /ps view in regions they are not a part of.
    default: op
  protectionstones.info:
    description: Allows players the use of /ps info.
    default: op
  protectionstones.info.others:
    description: Allows players to use /ps info in unowned regions.
    default: op
  protectionstones.get:
    description: Allows players the use of /ps get.
    default: op
  protectionstones.give:
    description: Allows players the use of /ps give (give protectionstones to others as admin).
    default: op
  protectionstones.count:
    description: Allows players the use of /ps count.
    default: op
  protectionstones.count.others:
    description: Allows players the use of /ps count [player].
    default: op
  protectionstones.list:
    description: Allows players the use of /ps list.
    default: op
  protectionstones.list.others:
    description: Allows players to do /ps list [player].
    default: op
  protectionstones.hide:
    description: Allow players to hide their ProtectionStones block.
    default: op
  protectionstones.unhide:
    description: Allow players to unhide their ProtectionStones block.
    default: op
  protectionstones.setparent:
    description: Allow access to /ps setparent.
    default: op
  protectionstones.setparent.others:
    description: Allow players to set their region to inherit properties from other regions they don't own.
    default: op
  protectionstones.name:
    description: Access to the /ps name command.
    default: op
  protectionstones.home:
    description: Access to the /ps home command.
    default: op
  protectionstones.sethome:
    description: Access to /ps sethome.
    default: op
  protectionstones.tp:
    description: Access to /ps tp command.
    default: op
  protectionstones.tp.bypasswait:
    description: Bypass the wait time set in the config for /ps home and /ps tp
    default: op
  protectionstones.tp.bypassprevent:
    description: Bypass prevent_teleport_in option in config
    default: op
  protectionstones.priority:
    description: Allows players to set their region's priority.
    default: op
  protectionstones.owners:
    description: Allows players to add or remove region owners. Allows players to use /ps info owners command.
    default: op
  protectionstones.members:
    description: Allows players to add or remove region members. Allows players to use /ps info members command.
    default: op
  protectionstones.flags:
    description: Allows players to set their region flags.
    default: op
  protectionstones.rent:
    description: Allows players to use the /ps rent command.
    default: op
  protectionstones.buysell:
    description: Allows players access to /ps buy and /ps sell.
    default: op
  protectionstones.tax:
    description: Allows players to access /ps tax commands.
    default: op
  protectionstones.toggle:
    description: Allows players to toggle ProtectionStones placement.
    default: op
  protectionstones.region:
    description: Allows players to use the /ps region commands.
    default: op
  protectionstones.merge:
    description: Allows players to merge their regions with other regions they own.
    default: op
  protectionstones.admin:
    description: This permission allows users to override all ProtectionStones regions and use /ps admin and /ps reload.
    default: op
  protectionstones.superowner:
    description: Allows players to override region permissions.
    default: op